INSERT INTO teachers(first_name, last_name, mobile)
VALUES ('john', 'barber', '0614842129'),
       ('steven', 'silva', '8210738564'),
       ('david', 'king', '1603599929'),
       ('scott', 'vega', '7621467364'),
       ('justin', 'dennis', '8899972263');

INSERT INTO subjects(name)
VALUES ('algebra'),
       ('geography'),
       ('english'),
       ('math'),
       ('music');

INSERT INTO teams(name)
VALUES ('g1'),
       ('g2'),
       ('g3');

INSERT INTO students(first_name, last_name, mobile, team_id)
VALUES ('alvin', 'gibson', '4153674206', (SELECT id FROM teams WHERE name = 'g1')),
       ('michael', 'scott', '2603558791', (SELECT id FROM teams WHERE name = 'g1')),
       ('james', 'herrera', '8074349940', (SELECT id FROM teams WHERE name = 'g1')),
       ('harry', 'arnold', '9308162099', (SELECT id FROM teams WHERE name = 'g2')),
       ('edwin', 'jackson', '2699368381', (SELECT id FROM teams WHERE name = 'g2')),
       ('edward', 'lopez', '0689379877', (SELECT id FROM teams WHERE name = 'g2')),
       ('floyd', 'mason', '1504427369', (SELECT id FROM teams WHERE name = 'g3')),
       ('richard', 'wolfe', '5002892885', (SELECT id FROM teams WHERE name = 'g3')),
       ('bruce', 'wilson', '9178297375', (SELECT id FROM teams WHERE name = 'g3'));

INSERT INTO lessons(topic, date, team_id, teacher_id, subject_id)
VALUES ('classifying polynomials',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g1'),
        (SELECT id FROM teachers WHERE first_name = 'john' AND last_name = 'barber'),
        (SELECT id FROM subjects WHERE name = 'algebra')),
       ('classifying polynomials',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g2'),
        (SELECT id FROM teachers WHERE first_name = 'john' AND last_name = 'barber'),
        (SELECT id FROM subjects WHERE name = 'algebra')),
       ('classifying polynomials',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g3'),
        (SELECT id FROM teachers WHERE first_name = 'john' AND last_name = 'barber'),
        (SELECT id FROM subjects WHERE name = 'algebra')),
       ('earthquake',
        TIMESTAMP '2021-09-01 10:30:00',
        (SELECT id FROM teams WHERE name = 'g1'),
        (SELECT id FROM teachers WHERE first_name = 'steven' AND last_name = 'silva'),
        (SELECT id FROM subjects WHERE name = 'geography')),
       ('earthquake',
        TIMESTAMP '2021-09-01 10:30:00',
        (SELECT id FROM teams WHERE name = 'g2'),
        (SELECT id FROM teachers WHERE first_name = 'steven' AND last_name = 'silva'),
        (SELECT id FROM subjects WHERE name = 'geography')),
       ('earthquake',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g3'),
        (SELECT id FROM teachers WHERE first_name = 'steven' AND last_name = 'silva'),
        (SELECT id FROM subjects WHERE name = 'geography')),
       ('climate change',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g1'),
        (SELECT id FROM teachers WHERE first_name = 'david' AND last_name = 'king'),
        (SELECT id FROM subjects WHERE name = 'english')),
       ('climate change',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g2'),
        (SELECT id FROM teachers WHERE first_name = 'david' AND last_name = 'king'),
        (SELECT id FROM subjects WHERE name = 'english')),
       ('climate change',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g3'),
        (SELECT id FROM teachers WHERE first_name = 'david' AND last_name = 'king'),
        (SELECT id FROM subjects WHERE name = 'english')),
       ('shapes and figures',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g1'),
        (SELECT id FROM teachers WHERE first_name = 'scott' AND last_name = 'vega'),
        (SELECT id FROM subjects WHERE name = 'math')),
       ('shapes and figures',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g2'),
        (SELECT id FROM teachers WHERE first_name = 'scott' AND last_name = 'vega'),
        (SELECT id FROM subjects WHERE name = 'math')),
       ('shapes and figures',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g3'),
        (SELECT id FROM teachers WHERE first_name = 'scott' AND last_name = 'vega'),
        (SELECT id FROM subjects WHERE name = 'math')),
       ('bass',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g1'),
        (SELECT id FROM teachers WHERE first_name = 'justin' AND last_name = 'dennis'),
        (SELECT id FROM subjects WHERE name = 'music')),
       ('bass',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g2'),
        (SELECT id FROM teachers WHERE first_name = 'justin' AND last_name = 'dennis'),
        (SELECT id FROM subjects WHERE name = 'music')),
       ('bass',
        TIMESTAMP '2021-09-01 9:00:00',
        (SELECT id FROM teams WHERE name = 'g3'),
        (SELECT id FROM teachers WHERE first_name = 'justin' AND last_name = 'dennis'),
        (SELECT id FROM subjects WHERE name = 'music'));


INSERT INTO performances(is_present, mark, student_id, lesson_id)
VALUES (true,
        80,
        (SELECT id FROM students WHERE first_name = 'alvin' AND last_name = 'gibson'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'alvin' AND last_name = 'gibson'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'alvin' AND last_name = 'gibson'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'alvin' AND last_name = 'gibson'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'alvin' AND last_name = 'gibson'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'michael' AND last_name = 'scott'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'michael' AND last_name = 'scott'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'michael' AND last_name = 'scott'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'michael' AND last_name = 'scott'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'michael' AND last_name = 'scott'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'james' AND last_name = 'herrera'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'james' AND last_name = 'herrera'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'james' AND last_name = 'herrera'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'james' AND last_name = 'herrera'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'james' AND last_name = 'herrera'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g1'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'harry' AND last_name = 'arnold'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'harry' AND last_name = 'arnold'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'harry' AND last_name = 'arnold'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'harry' AND last_name = 'arnold'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'harry' AND last_name = 'arnold'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edwin' AND last_name = 'jackson'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edwin' AND last_name = 'jackson'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edwin' AND last_name = 'jackson'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edwin' AND last_name = 'jackson'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edwin' AND last_name = 'jackson'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edward' AND last_name = 'lopez'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edward' AND last_name = 'lopez'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edward' AND last_name = 'lopez'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edward' AND last_name = 'lopez'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'edward' AND last_name = 'lopez'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g2'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'floyd' AND last_name = 'mason'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'floyd' AND last_name = 'mason'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'floyd' AND last_name = 'mason'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'floyd' AND last_name = 'mason'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'floyd' AND last_name = 'mason'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'richard' AND last_name = 'wolfe'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'richard' AND last_name = 'wolfe'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'richard' AND last_name = 'wolfe'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'richard' AND last_name = 'wolfe'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'richard' AND last_name = 'wolfe'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),

       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'bruce' AND last_name = 'wilson'),
        (SELECT id FROM lessons WHERE topic = 'classifying polynomials' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'bruce' AND last_name = 'wilson'),
        (SELECT id FROM lessons WHERE topic = 'earthquake' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'bruce' AND last_name = 'wilson'),
        (SELECT id FROM lessons WHERE topic = 'climate change' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'bruce' AND last_name = 'wilson'),
        (SELECT id FROM lessons WHERE topic = 'shapes and figures' AND team_id = (SELECT id FROM teams WHERE name = 'g3'))),
       (true,
        80,
        (SELECT id FROM students WHERE first_name = 'bruce' AND last_name = 'wilson'),
        (SELECT id FROM lessons WHERE topic = 'bass' AND team_id = (SELECT id FROM teams WHERE name = 'g3')));

UPDATE lessons SET last_modified_at = CURRENT_TIMESTAMP(0);
UPDATE lessons SET last_modified_by = 'admin';

UPDATE performances SET last_modified_at = CURRENT_TIMESTAMP(0);
UPDATE performances SET last_modified_by = 'admin';

UPDATE students SET last_modified_at = CURRENT_TIMESTAMP(0);
UPDATE students SET last_modified_by = 'admin';

UPDATE subjects SET last_modified_at = CURRENT_TIMESTAMP(0);
UPDATE subjects SET last_modified_by = 'admin';

UPDATE teachers SET last_modified_at = CURRENT_TIMESTAMP(0);
UPDATE teachers SET last_modified_by = 'admin';

UPDATE teams SET last_modified_at = CURRENT_TIMESTAMP(0);
UPDATE teams SET last_modified_by = 'admin';